Fix update feature and update README.md

diff --git a/hassctl b/hassctl
--- a/hassctl
+++ b/hassctl
@@ -1,20 +1,41 @@
 #!/bin/bash
 
-HASS_SERVICE="home-assistant*"
+update() {
+  sudo curl -s -S -o /usr/local/bin/hassctl https://raw.githubusercontent.com/dale3h/hassctl/master/hassctl && sudo chmod +x /usr/local/bin/hassctl
+  # Reserved for future changes to update function
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  # Reserved
+  echo "hassctl has been updated to the latest version"
+  exit 0
+}
+
+usage() {
+  echo "usage: $(basename $0) <start|stop|restart|kill|log|error|config|update>"
+  exit 1
+}
+
+hass_service="home-assistant*"
 
 if [ "$1" = "log" ]; then
-  clear && sudo journalctl ${@:2} -u "$HASS_SERVICE" | grep --color=always -iP '.*(error|errno|warning|exception|failure|failed|warn|except|fail).*|$'
+  clear && sudo journalctl ${@:2} -u "$hass_service" | grep --color=always -iP '.*(error|errno|warning|exception|failure|failed|warn|except|fail).*|$'
 elif [ "$1" = "error" ]; then
-  clear && sudo journalctl ${@:2} --no-pager -f -u "$HASS_SERVICE" | grep --color=always -iP '^--.*--$|^(?!.*Current job from).*(error|errno|warning|exception|failure|failed|warn|except|fail).*'
+  clear && sudo journalctl ${@:2} --no-pager -f -u "$hass_service" | grep --color=always -iP '^--.*--$|^(?!.*Current job from).*(error|errno|warning|exception|failure|failed|warn|except|fail).*'
 elif [ "$1" = "kill" ]; then
   ps aux | grep 'python' | grep 'hass' | grep -vE 'grep' | awk '{print $2}' | xargs kill -9
 elif [ "$1" = "config" ]; then
   $(which hass) --script check_config
 elif [ "$1" = "update" ]; then
-  wget -q http://pastebin.com/raw/CwXh0vfN -O- | tr -d '\r' | sudo tee /usr/local/bin/hassctl > /dev/null
-  sudo chown pi:pi /usr/local/bin/hassctl
-  chmod +x /usr/local/bin/hassctl
-  echo "hassctl has been updated."
+  update
 else
-  sudo systemctl $@ "$HASS_SERVICE"
+  sudo systemctl $@ "$hass_service"
 fi
