Partial Hass.io support

diff --git a/hassctl b/hassctl
--- a/hassctl
+++ b/hassctl
@@ -1,6 +1,10 @@
 #!/bin/bash
 
-HASSCTL_VERSION="1.2.1"
+# @todo Install Node.js on Hass.io if missing
+# @todo Install color-logviewer on Hass.io if missing
+# @todo Update log/error/debug/zwave commands for Hass.io
+
+HASSCTL_VERSION="1.3.0-alpha"
 
 debug() {
   (( $DEBUG )) && echo "$(basename $0): DEBUG:" "$@"
@@ -25,7 +29,13 @@ die() {
 }
 
 usage() {
-  echo "usage: $(basename $0) {help|version|start|stop|restart|kill|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    echo "usage (Hass.io): $(basename $0) {help|version|start|stop|restart|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
+  else
+    # Hass.io is not installed
+    echo "usage: $(basename $0) {help|version|start|stop|restart|kill|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
+  fi
   exit 1
 }
 
@@ -33,6 +43,9 @@ version() {
   echo "$HASSCTL_VERSION"
   exit 0
 }
+
+# Check for Hass.io CLI
+hassio=$(command -v /usr/bin/hassio)
 
 # Show usage if no arguments given
 if [[ $# -lt 1 ]]; then
@@ -42,6 +55,11 @@ fi
 # Report unimplemented command
 no_command() {
   warn "command not yet implemented: $1"
+  usage
+}
+
+no_command_hassio() {
+  warn "command not supported on hass.io: $1"
   usage
 }
 
@@ -85,38 +103,55 @@ read_config() {
   # Get this scripts full path
   HASSCTL_EXEC="$(realpath $0)"
 
-  # Confirm virtualenv path exists or is empty
-  VIRTUAL_ENV="${VIRTUAL_ENV-/srv/homeassistant}"
-  [[ -z "$VIRTUAL_ENV" ]] && warn "continuing without VIRTUAL_ENV"
-  [[ -z "$VIRTUAL_ENV" ]] || [[ -d "$VIRTUAL_ENV" ]] \
-    || die "$VIRTUAL_ENV: no such directory -- please update VIRTUAL_ENV in $HASSCTL_CONF"
+  # Confirm virtualenv path exists or is empty (if Hass.io not installed)
+  if [[ -z "$hassio" ]]; then
+    # Hass.io is not installed
+    VIRTUAL_ENV="${VIRTUAL_ENV-/srv/homeassistant}"
+    [[ -z "$VIRTUAL_ENV" ]] && warn "continuing without VIRTUAL_ENV"
+    [[ -z "$VIRTUAL_ENV" ]] || [[ -d "$VIRTUAL_ENV" ]] \
+      || die "$VIRTUAL_ENV: no such directory -- please update VIRTUAL_ENV in $HASSCTL_CONF"
+  fi
 
   # Confirm Home Assistant config path exists
-  HASS_CONFIG="${HASS_CONFIG:-/home/homeassistant/.homeassistant}"
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    HASS_CONFIG="/config"
+    OZW_LOG="$HASS_CONFIG/OZW_Log.txt"
+  else
+    # Hass.io is not installed
+    HASS_CONFIG="${HASS_CONFIG:-/home/homeassistant/.homeassistant}"
+  fi
+
   [[ -z "$HASS_CONFIG" ]] || [[ -d "$HASS_CONFIG" ]] \
     || die "$HASS_CONFIG: no such directory -- please update HASS_CONFIG in $HASSCTL_CONF"
 
-  # Verify user exists
-  HASS_USER="${HASS_USER:-homeassistant}"
-  id -u "$HASS_USER" >/dev/null || die "$HASS_USER: no such user -- please update HASS_USER in $HASSCTL_CONF"
+  # Verify user exists (if Hass.io not installed)
+  if [[ -z "$hassio" ]]; then
+    # Hass.io is not installed
+    HASS_USER="${HASS_USER:-homeassistant}"
+    id -u "$HASS_USER" >/dev/null || die "$HASS_USER: no such user -- please update HASS_USER in $HASSCTL_CONF"
+  fi
 
   HASSCTL_BRANCH="${HASSCTL_BRANCH:-master}"
   HASS_SERVICE="${HASS_SERVICE:-home*assistant*}"
   OZW_LOG="${OZW_LOG:-$HASS_CONFIG/OZW_Log.txt}"
 
-  if [[ ! -z "$VIRTUAL_ENV" ]]; then
-    PIP_EXEC="${PIP_EXEC:-$VIRTUAL_ENV/bin/pip3}"
-    HASS_EXEC="${HASS_EXEC:-$VIRTUAL_ENV/bin/hass}"
-  else
-    PIP_EXEC="${PIP_EXEC:-$(which pip3)}"
-    HASS_EXEC="${HASS_EXEC:-$(which hass)}"
+  if [[ -z "$hassio" ]]; then
+    # Hass.io is not installed
+    if [[ -n "$VIRTUAL_ENV" ]]; then
+      PIP_EXEC="${PIP_EXEC:-$VIRTUAL_ENV/bin/pip3}"
+      HASS_EXEC="${HASS_EXEC:-$VIRTUAL_ENV/bin/hass}"
+    else
+      PIP_EXEC="${PIP_EXEC:-$(command -v pip3)}"
+      HASS_EXEC="${HASS_EXEC:-$(command -v hass)}"
+    fi
+
+    [[ -f "$PIP_EXEC" ]] || die "$PIP_EXEC: no such file -- please update PIP_EXEC in $HASSCTL_CONF"
+    [[ -x "$PIP_EXEC" ]] || die "$PIP_EXEC: file not executable -- please update PIP_EXEC in $HASSCTL_CONF"
+
+    [[ -f "$HASS_EXEC" ]] || die "$HASS_EXEC: no such file -- please update HASS_EXEC in $HASSCTL_CONF"
+    [[ -x "$HASS_EXEC" ]] || die "$HASS_EXEC: file not executable -- please update HASS_EXEC in $HASSCTL_CONF"
   fi
-
-  [[ -f "$PIP_EXEC" ]] || die "$PIP_EXEC: no such file -- please update PIP_EXEC in $HASSCTL_CONF"
-  [[ -x "$PIP_EXEC" ]] || die "$PIP_EXEC: file not executable -- please update PIP_EXEC in $HASSCTL_CONF"
-
-  [[ -f "$HASS_EXEC" ]] || die "$HASS_EXEC: no such file -- please update HASS_EXEC in $HASSCTL_CONF"
-  [[ -x "$HASS_EXEC" ]] || die "$HASS_EXEC: file not executable -- please update HASS_EXEC in $HASSCTL_CONF"
 
   return 0
 }
@@ -191,59 +226,154 @@ update_hass() {
   read_config
   local VERSION="$1"
 
-  if [[ ! -z $VERSION ]]; then
+  if [[ -n $VERSION ]]; then
     VERSION="==$VERSION"
   fi
 
-  maybe_exec_as "$HASS_USER" "$PIP_EXEC" install --upgrade homeassistant$VERSION
-  exit $?
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    if [[ -n "$VERSION" ]]; then
+      warn "version argument not supported on hass.io"
+    else
+      debug "$hassio homeassistant update"
+      $hassio homeassistant update
+    fi
+  else
+    # Hass.io is not installed
+    maybe_exec_as "$HASS_USER" "$PIP_EXEC" install --upgrade homeassistant$VERSION
+    exit $?
+  fi
 }
 
 # Run hass check_config script
 check_config() {
   read_config
-  maybe_exec_as "$HASS_USER" "$HASS_EXEC" --script check_config -c "$HASS_CONFIG" "$@"
+
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    debug "$hassio homeassistant check"
+    $hassio homeassistant check
+  else
+    # Hass.io is not installed
+    maybe_exec_as "$HASS_USER" "$HASS_EXEC" --script check_config -c "$HASS_CONFIG" "$@"
+  fi
 }
 
 # Show Home Assistant raw log
 hass_raw_log() {
   read_config
-  debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\""
-  clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE"
+
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    hass_raw_log_hassio "$@"
+  else
+    # Hass.io is not installed
+    debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\""
+    clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE"
+  fi
+}
+
+hass_raw_log_hassio() {
+  read_config
+
+  HASS_LOG="$HASS_CONFIG/home-assistant.log"
+
+  [[ -f "$HASS_LOG" ]] || die "$HASS_LOG: no such file"
+  [[ -r "$HASS_LOG" ]] || die "$HASS_LOG: file not readable"
+
+  clear && $tail "$@" -f "$HASS_LOG" | $sed \
+    -e 's/\(.*TRACE.*\)/\o033[35m\1\o033[39m/' \
+    -e 's/\(.*DEBUG.*\)/\o033[36m\1\o033[39m/' \
+    -e 's/\(.*INFO.*\)/\o033[32m\1\o033[39m/' \
+    -e 's/\(.*WARN.*\)/\o033[33m\1\o033[39m/' \
+    -e 's/\(.*ERROR.*\)/\o033[31m\1\o033[39m/'
 }
 
 # Show Home Assistant error log
 hass_error_log() {
   read_config
-  debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'"
-  clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'
+
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    no_command_hassio "error"
+  else
+    # Hass.io is not installed
+    debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'"
+    clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'
+  fi
 }
 
 # Show Home Assistant debug log
 hass_debug_log() {
   read_config
-  debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'"
-  clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'
+
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    no_command_hassio "debug"
+  else
+    # Hass.io is not installed
+    debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'"
+    clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'
+  fi
 }
 
 # Kill Home Assistant service
 hass_kill() {
   read_config
-  debug "sudo $systemctl kill --signal=SIGKILL \"$HASS_SERVICE\""
-  sudo $systemctl kill --signal=SIGKILL "$HASS_SERVICE"
+
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    no_command_hassio "kill"
+  else
+    # Hass.io is not installed
+    debug "sudo $systemctl kill --signal=SIGKILL \"$HASS_SERVICE\""
+    sudo $systemctl kill --signal=SIGKILL "$HASS_SERVICE"
+  fi
 }
 
 # Kill Home Assistant using alternative method
 hass_kill_alt() {
-  debug "ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9"
-  ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    no_command_hassio "kill-alt"
+  else
+    # Hass.io is not installed
+    debug "ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9"
+    ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9
+  fi
 }
 
 # Pass commands to Home Assistant service
 systemctl_cmd() {
+  if [[ -n "$hassio" ]]; then
+    # Hass.io is installed
+    hassio_cmd "$@"
+  else
+    # Hass.io is not installed
+    read_config
+    debug "sudo $systemctl \"$@\" \"$HASS_SERVICE\""
+    sudo $systemctl "$@" "$HASS_SERVICE"
+  fi
+}
+
+hassio_cmd() {
   read_config
-  debug "sudo $systemctl \"$@\" \"$HASS_SERVICE\""
-  sudo $systemctl "$@" "$HASS_SERVICE"
+
+  case "$1" in
+    restart|start|stop)
+      debug "$hassio homeassistant \"$@\""
+      $hassio homeassistant "$@"
+      ;;
+
+    status)
+      debug "$hassio homeassistant info"
+      $hassio homeassistant info
+      ;;
+
+    *)
+      no_command_hassio "$1"
+      ;;
+  esac
 }
 
 # Show Z-Wave log
