Partial Hass.io support

diff --git a/hassctl b/hassctl
--- a/hassctl
+++ b/hassctl
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-# @todo Install Node.js on Hass.io if missing
-# @todo Install color-logviewer on Hass.io if missing
-# @todo Update log/error/debug/zwave commands for Hass.io
+# @todo Update error/debug/zwave commands for Hass.io
 
 HASSCTL_VERSION="1.3.0-alpha"
 
@@ -29,13 +27,14 @@ die() {
 }
 
 usage() {
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    echo "usage (Hass.io): $(basename $0) {help|version|start|stop|restart|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
-  else
-    # Hass.io is not installed
-    echo "usage: $(basename $0) {help|version|start|stop|restart|kill|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
-  fi
+  $HASSIO && usage_hassio
+
+  echo "usage: $(basename $0) {help|version|start|stop|restart|kill|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
+  exit 1
+}
+
+usage_hassio() {
+  echo "usage (Hass.io): $(basename $0) {help|version|start|stop|restart|log|error|debug|zwave|config|update-hassctl|update-hass|backup|service}" 2>&1
   exit 1
 }
 
@@ -46,6 +45,11 @@ version() {
 
 # Check for Hass.io CLI
 hassio=$(command -v /usr/bin/hassio)
+if [[ -n "$hassio" ]]; then
+  HASSIO=true
+else
+  HASSIO=false
+fi
 
 # Show usage if no arguments given
 if [[ $# -lt 1 ]]; then
@@ -72,6 +76,7 @@ systemctl=/bin/systemctl
 journalctl=/bin/journalctl
 tail=/usr/bin/tail
 sed=/bin/sed
+apk=/sbin/apk
 
 # Get the current username
 me="$(whoami)"
@@ -104,7 +109,7 @@ read_config() {
   HASSCTL_EXEC="$(realpath $0)"
 
   # Confirm virtualenv path exists or is empty (if Hass.io not installed)
-  if [[ -z "$hassio" ]]; then
+  if ! $HASSIO; then
     # Hass.io is not installed
     VIRTUAL_ENV="${VIRTUAL_ENV-/srv/homeassistant}"
     [[ -z "$VIRTUAL_ENV" ]] && warn "continuing without VIRTUAL_ENV"
@@ -113,7 +118,7 @@ read_config() {
   fi
 
   # Confirm Home Assistant config path exists
-  if [[ -n "$hassio" ]]; then
+  if $HASSIO; then
     # Hass.io is installed
     HASS_CONFIG="/config"
     OZW_LOG="$HASS_CONFIG/OZW_Log.txt"
@@ -126,7 +131,7 @@ read_config() {
     || die "$HASS_CONFIG: no such directory -- please update HASS_CONFIG in $HASSCTL_CONF"
 
   # Verify user exists (if Hass.io not installed)
-  if [[ -z "$hassio" ]]; then
+  if ! $HASSIO; then
     # Hass.io is not installed
     HASS_USER="${HASS_USER:-homeassistant}"
     id -u "$HASS_USER" >/dev/null || die "$HASS_USER: no such user -- please update HASS_USER in $HASSCTL_CONF"
@@ -136,7 +141,7 @@ read_config() {
   HASS_SERVICE="${HASS_SERVICE:-home*assistant*}"
   OZW_LOG="${OZW_LOG:-$HASS_CONFIG/OZW_Log.txt}"
 
-  if [[ -z "$hassio" ]]; then
+  if ! $HASSIO; then
     # Hass.io is not installed
     if [[ -n "$VIRTUAL_ENV" ]]; then
       PIP_EXEC="${PIP_EXEC:-$VIRTUAL_ENV/bin/pip3}"
@@ -230,7 +235,7 @@ update_hass() {
     VERSION="==$VERSION"
   fi
 
-  if [[ -n "$hassio" ]]; then
+  if $HASSIO; then
     # Hass.io is installed
     if [[ -n "$VERSION" ]]; then
       warn "version argument not supported on hass.io"
@@ -240,7 +245,10 @@ update_hass() {
     fi
   else
     # Hass.io is not installed
-    maybe_exec_as "$HASS_USER" "$PIP_EXEC" install --upgrade homeassistant$VERSION
+    UPDATE_PRE_RELEASE=
+    ( [[ "$VERSION" == "beta" ]] || [[ -n "$HASS_UPDATE_BETA" ]] ) && UPDATE_PRE_RELEASE="--pre"
+
+    maybe_exec_as "$HASS_USER" "$PIP_EXEC" install --upgrade $UPDATE_PRE_RELEASE homeassistant$VERSION
     exit $?
   fi
 }
@@ -249,7 +257,7 @@ update_hass() {
 check_config() {
   read_config
 
-  if [[ -n "$hassio" ]]; then
+  if $HASSIO; then
     # Hass.io is installed
     debug "$hassio homeassistant check"
     $hassio homeassistant check
@@ -263,99 +271,109 @@ check_config() {
 hass_raw_log() {
   read_config
 
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    hass_raw_log_hassio "$@"
-  else
-    # Hass.io is not installed
-    debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\""
-    clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE"
-  fi
-}
+  $HASSIO && hass_raw_log_hassio "$@"
 
-hass_raw_log_hassio() {
-  read_config
-
-  HASS_LOG="$HASS_CONFIG/home-assistant.log"
-
-  [[ -f "$HASS_LOG" ]] || die "$HASS_LOG: no such file"
-  [[ -r "$HASS_LOG" ]] || die "$HASS_LOG: file not readable"
-
-  clear && $tail "$@" -f "$HASS_LOG" | $sed \
-    -e 's/\(.*TRACE.*\)/\o033[35m\1\o033[39m/' \
-    -e 's/\(.*DEBUG.*\)/\o033[36m\1\o033[39m/' \
-    -e 's/\(.*INFO.*\)/\o033[32m\1\o033[39m/' \
-    -e 's/\(.*WARN.*\)/\o033[33m\1\o033[39m/' \
-    -e 's/\(.*ERROR.*\)/\o033[31m\1\o033[39m/'
+  debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\""
+  clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE"
 }
 
 # Show Home Assistant error log
 hass_error_log() {
   read_config
 
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    no_command_hassio "error"
-  else
-    # Hass.io is not installed
-    debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'"
-    clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'
-  fi
+  $HASSIO && no_command_hassio "error"
+
+  debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'"
+  clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '^  .*$|^(?!.*is_failed=)(?!.*service=remove_failed_node)(?!.*service=replace_failed_node).*(error|errno|warning|exception|failure|failed|warn|except|fail|traceback).*'
 }
 
 # Show Home Assistant debug log
 hass_debug_log() {
   read_config
 
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    no_command_hassio "debug"
-  else
-    # Hass.io is not installed
-    debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'"
-    clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'
-  fi
+  $HASSIO && no_command_hassio "debug"
+
+  debug "clear && sudo $journalctl \"$@\" --no-pager -o cat -fu \"$HASS_SERVICE\" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'"
+  clear && sudo $journalctl "$@" --no-pager -o cat -fu "$HASS_SERVICE" | grep -iP '[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} DEBUG'
 }
 
 # Kill Home Assistant service
 hass_kill() {
   read_config
 
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    no_command_hassio "kill"
-  else
-    # Hass.io is not installed
-    debug "sudo $systemctl kill --signal=SIGKILL \"$HASS_SERVICE\""
-    sudo $systemctl kill --signal=SIGKILL "$HASS_SERVICE"
-  fi
+  $HASSIO && no_command_hassio "kill"
+
+  debug "sudo $systemctl kill --signal=SIGKILL \"$HASS_SERVICE\""
+  sudo $systemctl kill --signal=SIGKILL "$HASS_SERVICE"
 }
 
 # Kill Home Assistant using alternative method
 hass_kill_alt() {
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    no_command_hassio "kill-alt"
-  else
-    # Hass.io is not installed
-    debug "ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9"
-    ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9
-  fi
+  $HASSIO && no_command_hassio "kill-alt"
+
+  debug "ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9"
+  ps aux | grep python3 | grep hass | grep -vE grep | awk '{print $2}' | xargs kill -9
 }
 
 # Pass commands to Home Assistant service
 systemctl_cmd() {
-  if [[ -n "$hassio" ]]; then
-    # Hass.io is installed
-    hassio_cmd "$@"
-  else
-    # Hass.io is not installed
-    read_config
-    debug "sudo $systemctl \"$@\" \"$HASS_SERVICE\""
-    sudo $systemctl "$@" "$HASS_SERVICE"
+  $HASSIO && hassio_cmd "$@"
+
+  read_config
+  debug "sudo $systemctl \"$@\" \"$HASS_SERVICE\""
+  sudo $systemctl "$@" "$HASS_SERVICE"
+}
+
+# Show Z-Wave log
+zwave_log() {
+  read_config
+
+  [[ -f "$OZW_LOG" ]] || die "$OZW_LOG: no such file -- please update OZW_LOG in $HASSCTL_CONF"
+  [[ -r "$OZW_LOG" ]] || die "$OZW_LOG: file not readable -- please update OZW_LOG in $HASSCTL_CONF"
+
+  debug "clear && $tail \"$@\" -f \"$OZW_LOG\""
+  clear && $tail "$@" -f "$OZW_LOG" | $sed \
+    -e 's/\(.*Always,.*\)/\o033[35m\1\o033[39m/' \
+    -e 's/\(.*Detail,.*\)/\o033[36m\1\o033[39m/' \
+    -e 's/\(.*Info,.*\)/\o033[32m\1\o033[39m/' \
+    -e 's/\(.*Warning,.*\)/\o033[33m\1\o033[39m/' \
+    -e 's/\(.*Error,.*\)/\o033[31m\1\o033[39m/'
+}
+
+# Initialization for npm
+npm_init() {
+  # Check for npm
+  npm=$(command -v npm)
+
+  if [[ -z "$npm" ]]; then
+    $apk add nodejs
+    npm=$(command -v npm)
+    [[ -n "$npm" ]] || die "could not install nodejs"
   fi
 }
 
+# Initialization for clog
+clog_init() {
+  # Initialize npm
+  npm_init
+
+  # Check for color-logviewer
+  clog=$(command -v color-logviewer)
+
+  if [[ -z "$clog" ]]; then
+    $npm install -g color-logviewer
+    clog=$(command -v color-logviewer)
+    [[ -n "$clog" ]] || die "could not install color-logviewer"
+  fi
+
+  # Get log colors
+  LOG_COLORS="${LOG_COLORS:-ERROR=red,WARN=yellow,INFO=green,DEBUG=cyan,TRACE=blue}"
+
+  # Default arguments for clog
+  clog_args="-c $LOG_COLORS"
+}
+
+# Special handling for Hass.io
 hassio_cmd() {
   read_config
 
@@ -374,22 +392,20 @@ hassio_cmd() {
       no_command_hassio "$1"
       ;;
   esac
+
+  exit 0
 }
 
-# Show Z-Wave log
-zwave_log() {
+hass_raw_log_hassio() {
   read_config
 
-  [[ -f "$OZW_LOG" ]] || die "$OZW_LOG: no such file -- please update OZW_LOG in $HASSCTL_CONF"
-  [[ -r "$OZW_LOG" ]] || die "$OZW_LOG: file not readable -- please update OZW_LOG in $HASSCTL_CONF"
+  HASS_LOG="$HASS_CONFIG/home-assistant.log"
 
-  debug "clear && $tail \"$@\" -f \"$OZW_LOG\""
-  clear && $tail "$@" -f "$OZW_LOG" | $sed \
-    -e 's/\(.*Always,.*\)/\o033[35m\1\o033[39m/' \
-    -e 's/\(.*Detail,.*\)/\o033[36m\1\o033[39m/' \
-    -e 's/\(.*Info,.*\)/\o033[32m\1\o033[39m/' \
-    -e 's/\(.*Warning,.*\)/\o033[33m\1\o033[39m/' \
-    -e 's/\(.*Error,.*\)/\o033[31m\1\o033[39m/'
+  [[ -f "$HASS_LOG" ]] || die "$HASS_LOG: no such file"
+  [[ -r "$HASS_LOG" ]] || die "$HASS_LOG: file not readable"
+
+  clog_init
+  clear && $clog $clog_args "$HASS_LOG"
 }
 
 # Process arguments
